version: '3'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./.docker/postgres/:/var/lib/postgres-api/data
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        networks:
            - network

networks:
    network:
        driver: bridge
